name: Check Docs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Spelling
        uses: devcontainers/ci@v0.2
        with:
          runCmd: npm run spellcheck

      - name: Check Formatting
        uses: devcontainers/ci@v0.2
        with:
          runCmd: npm run format:check

      - name: Build Site
        uses: devcontainers/ci@v0.2
        with:
          runCmd: npm run build

      - name: Check Size
        uses: devcontainers/ci@v0.2
        with:
          runCmd: npm run check-size

